### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by jingyanw** [albanie/mcnNMS#1]
Hi,

Thanks for developing the code. I had two issues with compilation:

1) `flags.cc` (https://github.com/albanie/mcnNMS/blob/master/compile_mcnNMS.m#L54) seems to be removed from `vl_compilenn` now, which gives an error. I think it should be `flags.base` (?).

2) I had an error at https://github.com/albanie/mcnNMS/blob/master/matlab/src/vl_nnbboxnms.cu#L19:
```
mcnNMS/matlab/src/vl_nnbboxnms.cu:19:30: fatal error: bits/nnbboxnms.hpp: No such file or directory
 #include <bits/nnbboxnms.hpp>
```

Changing it to `"bits/nnbboxnms.hpp"` (using quotation marks) worked.

After fixing the two above, the compilation seems to work.

**Comment by albanie** [comment]
Thanks a lot :) The updated compile script should hopefully fix these.
